<?php

namespace AppBundle\Repository;

/**
 * Property_OwnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Property_OwnerRepository extends \Doctrine\ORM\EntityRepository
{
}
